### PR TITLE
tickets#show: Uniquify photos before listing them

### PR DESCRIPTION
**Pull request by rye**
This may resolve an issue with photos being listed incorrectly. I have no test server/test database to test this on, but I believe this should help with the issue.

### CODE REVIEW

**Comment by cg505** [comment]
Why did you close this?

**Comment by rye** [comment]
Because GitHub automatically added a bunch more commits to it.

**Comment by cg505** [comment]
You are supposed to do things on a branch.

**Comment by rye** [comment]
I know.

**Pull request closed without merging**
